name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write      # Required for GitHub Pages deployment
  id-token: write   # Required for GitHub Pages deployment

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Setup reports directory
        run: mkdir -p cypress/reports

      - name: Run Cypress tests
        run: npm run test:with-report
        continue-on-error: true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

  deploy-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download test report artifact
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install report generator
        run: npm install mochawesome-report-generator

      - name: Generate HTML report
        run: |
          if [ -f cypress/reports/mochawesome.json ]; then
            npx marge cypress/reports/mochawesome.json -f report -o cypress/reports/html
          else
            mkdir -p cypress/reports/html
            echo "<html><body><h1>No test reports available</h1></body></html>" > cypress/reports/html/index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'cypress/reports/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4